quarkus:
  rest-client:
    streamer:
      url: localhost:8081/service4
  http:
    port: 8080

app:
  config:
    map-configs:
      - name: Bob
        foo: thing
        bar: false
      - name: Tim
        baz: stuff
        qux: 3
